### ISSUE TITLE
Error creating output files

### ISSUE THREAD

**Issue by sliceofbytes** [hero-page/hero-ml#8]
Error creating output file on windows.

H:\
λ npx hero run --number_of_colors 4 Colors.heroml
[ 'number_of_colors' ]
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Error: Error: ENOENT: no such file or directory, open 'H:\outputs\response_2023-08-17T04:07:07.666Z.json.md'
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at writeMarkdownOutput (C:\Users\slice\AppData\Roaming\npm\node_modules\heroml\dist\cli.js:131:18)
    at Object.<anonymous> (C:\Users\slice\AppData\Roaming\npm\node_modules\heroml\dist\cli.js:204:17)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\slice\AppData\Roaming\npm\node_modules\heroml\dist\cli.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'H:\\outputs\\response_2023-08-17T04:07:07.666Z.json.md'
}

I've checked folder permissions and tried it in a couple different places, also tried -o etc..

**Comment by kingmeers** [comment]
Hm that's odd! I vaguely remember creating the outputs/ directory if it doesn't exist in the code, does `outputs/` exist in the directory you're running this script?
